export interface EventData {
  id: string;
  title: string;
  location: string;
  date: string;
  audience: string;
  logo: string;
  tags: string[];
  isFastTrack?: boolean;
}

export const mockEvent: EventData[] = [
  {
    id: "FT1",
    title: "Innovation Summit Asia 2024",
    location: "Jakarta",
    date: "3–5 Januari 2024",
    audience: "Profesional",
    logo: "/logo1.png",
    tags: [">10 Juta", "Dana", "Besar", "Offline"],
    isFastTrack: true,
  },
  {
    id: "FT2",
    title: "Future Tech Expo 2024",
    location: "Bandung",
    date: "17–20 Februari 2024",
    audience: "Mahasiswa",
    logo: "/logo2.png",
    tags: ["5–10 Juta", "Produk", "Sedang", "Offline"],
    isFastTrack: true,
  },
  {
    id: "FT3",
    title: "Startup Founder Day",
    location: "Surabaya",
    date: "8–10 Maret 2024",
    audience: "Komunitas",
    logo: "/logo3.png",
    tags: ["3–6 Juta", "Dana", "Sedang", "Online"],
    isFastTrack: true,
  },
  {
    id: "FT4",
    title: "National Creativity Week",
    location: "Semarang",
    date: "25–27 April 2024",
    audience: "Umum",
    logo: "/logo4.png",
    tags: ["2–3 Juta", "Dana", "Kecil", "Offline"],
    isFastTrack: true,
  },
  {
    id: "FT5",
    title: "Digital Innovation Hackfest",
    location: "Yogyakarta",
    date: "12–14 Mei 2024",
    audience: "Developer",
    logo: "/logo5.png",
    tags: ["5–10 Juta", "Produk", "Sedang", "Offline"],
    isFastTrack: true,
  },
  {
    id: "EV6",
    title: "Tech Expo 2024",
    location: "Jakarta",
    date: "20–21 Mei 2024",
    audience: "Profesional",
    logo: "/logo2.png",
    tags: ["5–10 Juta", "Dana", "Sedang", "Online"],
  },
  {
    id: "EV7",
    title: "Startup Pitch Day",
    location: "Bandung",
    date: "10–11 Juni 2024",
    audience: "Komunitas",
    logo: "/logo3.png",
    tags: ["1–2 Juta", "Produk", "Kecil", "Offline"],
  },
  {
    id: "EV8",
    title: "Solo Event Global Tech",
    location: "Surakarta",
    date: "13–15 Agustus 2024",
    audience: "Mahasiswa",
    logo: "/logo1.png",
    tags: ["2–3 Juta", "Dana", "Besar", "Offline"],
  },
  {
    id: "EV9",
    title: "Digital Startup Conference",
    location: "Jakarta",
    date: "23–25 Juli 2024",
    audience: "Founder",
    logo: "/logo4.png",
    tags: [">10 Juta", "Produk", "Besar", "Offline"],
  },
  {
    id: "EV10",
    title: "Youth Creative Festival",
    location: "Solo",
    date: "30–31 Juli 2024",
    audience: "Pelajar",
    logo: "/logo6.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Offline"],
  },
  {
    id: "EV11",
    title: "EduTech Summit",
    location: "Surabaya",
    date: "8–9 Agustus 2024",
    audience: "Guru",
    logo: "/logo7.png",
    tags: ["3–5 Juta", "Produk", "Sedang", "Online"],
  },
  {
    id: "EV12",
    title: "Gaming Creator MeetUp",
    location: "Jakarta",
    date: "15–17 September 2024",
    audience: "Gamer",
    logo: "/logo8.png",
    tags: ["1–2 Juta", "Produk", "Kecil", "Offline"],
  },
  {
    id: "EV13",
    title: "Business Leadership Forum",
    location: "Medan",
    date: "28–30 September 2024",
    audience: "CEO",
    logo: "/logo9.png",
    tags: [">10 Juta", "Dana", "Besar", "Offline"],
  },
  {
    id: "EV14",
    title: "Music & Festival Expo",
    location: "Bali",
    date: "5–7 Oktober 2024",
    audience: "Umum",
    logo: "/logo10.png",
    tags: ["3–5 Juta", "Dana", "Sedang", "Offline"],
  },
  {
    id: "EV15",
    title: "AI & Robotics Week",
    location: "Jakarta",
    date: "10–12 Oktober 2024",
    audience: "Engineer",
    logo: "/logo11.png",
    tags: [">10 Juta", "Produk", "Besar", "Offline"],
  },
  {
    id: "EV16",
    title: "Indie Developer Showcase",
    location: "Malang",
    date: "18–19 Oktober 2024",
    audience: "Indie Dev",
    logo: "/logo12.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Online"],
  },
  {
    id: "EV17",
    title: "Cybersecurity Awareness Day",
    location: "Jakarta",
    date: "2–3 November 2024",
    audience: "IT Officer",
    logo: "/logo13.png",
    tags: ["3–6 Juta", "Produk", "Sedang", "Offline"],
  },
  {
    id: "EV18",
    title: "Creative Art Expo",
    location: "Bandung",
    date: "12–14 November 2024",
    audience: "Seni",
    logo: "/logo14.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Offline"],
  },
  {
    id: "EV19",
    title: "National Media Summit",
    location: "Jakarta",
    date: "20–22 November 2024",
    audience: "Media",
    logo: "/logo15.png",
    tags: ["3–5 Juta", "Produk", "Sedang", "Online"],
  },
  {
    id: "EV20",
    title: "Social Impact Conference",
    location: "Semarang",
    date: "1–3 Desember 2024",
    audience: "Komunitas",
    logo: "/logo16.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Offline"],
  },
];
export const mockProposal: EventData[] = [
  {
    id: "P1",
    title: "Creator Mini Expo",
    location: "Jakarta",
    date: "11–12 Januari 2024",
    audience: "Umum",
    logo: "/logo3.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Offline"],
    isFastTrack: true, // MINIMAL 1 FASTTRACK
  },
  {
    id: "P2",
    title: "Campus Innovation Day",
    location: "Bandung",
    date: "5–7 Februari 2024",
    audience: "Mahasiswa",
    logo: "/logo4.png",
    tags: ["2–3 Juta", "Produk", "Kecil", "Online"],
  },
  {
    id: "P3",
    title: "Youth Developer Gathering",
    location: "Surabaya",
    date: "8–9 Maret 2024",
    audience: "Developer",
    logo: "/logo5.png",
    tags: ["3–6 Juta", "Dana", "Sedang", "Offline"],
  },
  {
    id: "P4",
    title: "National StartUp Meetup",
    location: "Solo",
    date: "1–2 April 2024",
    audience: "Startup",
    logo: "/logo6.png",
    tags: ["1–2 Juta", "Dana", "Kecil", "Offline"],
  },
  {
    id: "P5",
    title: "Design & Creator Fest",
    location: "Malang",
    date: "22–23 April 2024",
    audience: "Content Creator",
    logo: "/logo7.png",
    tags: ["1–2 Juta", "Produk", "Kecil", "Online"],
  },
];
